service: auction-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTIONS_TABLE : AuctionsTable-${self:provider.stage}
  versionFunctions: false
  httpApi:
    cors:
      allowedOrigins: "*"
      allowedHeaders: "*"

  # sets permissions for lambda functions
  # each lambda has its own iam role
  iam:
    role:
      statements:
        # AuctionsTableIAM:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          #can  use Amazon Resource name(ARN) for specific table
          Resource: '*' 
            # !Join ['/,', ['${self:custom.AuctionsTable.arn}','index','statusAndEndDate']]
            # - ${self:custom.AuctionsTable.arn}
            # - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AcountId}:table/AuctionsTable 


# DynamoDB Table Setup
resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: endingAt
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: statusAndEndDate
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: endingAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

# list of lambda functions
# contains where to find handler, method, and path
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - httpApi:
          method: GET
          path: /auctions

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - httpApi:
          method: GET
          path: /auction/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          method: PATCH
          path: /auction/{id}/bid

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)

plugins:
  - serverless-offline
  - serverless-plugin-typescript


# allow for custom values
custom:
  serverless-offline:
      httpPort: 8080
  AuctionsTable: 
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
 
  